name: Mediaportal / Release

on:
  push:
    # On Tag / Release by Mask
    tags:
      - "Release_*"

jobs:
  build:
    uses: ./.github/workflows/mediaportal.yml
  
  release:
    name: Release Mediaportal
    needs: build
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: Mediaportal setup file
          path: release-files

      - name: 7z Artifacts
        run: |
          for i in *.exe;do 7z a -tZip ${i%.exe}.zip $i;done
        working-directory: release-files

      - name: Check artifacts
        run: |
          ls -l
        working-directory: release-files

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-files/MediaPortalSetup_*.zip

  codeql:
    uses: ./.github/workflows/workflow_codeql.yml
    needs: [build, release]
    permissions:
      security-events: write
